version: '3'

services:
  db: 
    image: postgres
    container_name: law-modeling-db
    ports:
      - 5434:5432
    env_file:
      - ./env/dev.env

  neo4j:
    image: neo4j
    container_name: law-modeling-graph
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    environment:
      - NEO4J_AUTH=none
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.\\\*
      - NEO4J_server_config_strict__validation_enabled=false
      - NEO4J_dbms_unmanaged__extension__classes=n10s.endpoint=/rdf
      # - NEO4J_PLUGINS=["graph-data-science"]
      # - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
    # env_file:
    #   - ./env/dev.env
    volumes:
      - ./docker/graph/plugins:/var/lib/neo4j/plugins
      - ./docker/graph/data:/data/rdf
      - ./docker/graph/data/:/var/lib/neo4j/import
      - ./docker/graph/config/apoc.conf:/var/lib/neo4j/conf/apoc.conf
      # - ./docker/graph/conf:/var/lib/neo4j/conf
    restart: always


  # cache:
  #   image: redis
  #   container_name: law-modeling-cache
  #   profiles:
  #     - db
  #   ports:
  #     - 6379:6379